### ISSUE TITLE
Adding check to not allow self approval.

### ISSUE THREAD

**Issue by utsav14nov** [goto/guardian#175]
**Summary**
Currently if appeal creator himself/herself is one of the approver in any approval step, He/She can approve that approval step for their own appeal. As per the audit doc, this should not happen as it violates SOD( Segregation of duties) rule.
 
**Proposed solution**
As discussed and proposed, We will be adding check in `UpdateApproval` api that `if appeal.creator == approvalAction.actor` then return error `requestor is not allowed to approve their own request`. This will be config based where configuration flag `dont_allow_self_approval:true` will be added to approval steps in policy where self approval is not needed. Policy step not having this flag will be eligible for self approval and hence backward compatible according to the current scenario.   

Eg policy step:
```
-   name: sample_example_step
    description: sample example step
    strategy: manual
    dont_allow_self_approval: true
    approvers:
      - x.y@z.com
```

**Additional context**
For the users who land up in above scenario and are the only approver in that approval step, engineering team be adding alternate approver for that step for that appeal.
