### ISSUE TITLE
add check for duplicates in iam provider roles

### ISSUE THREAD

**Issue by bsushmith** [goto/guardian#92]
**Description**
If a duplicate role is added in gcloud iam provider file,  the provider works fine without issues. One should not be able to add a duplicate role

This provider gets applied without issues even though the viewer role is duplicated. there must be a id based check here to avert this case.
```yaml
resources:
  - type: project
    policy:
      id: mtrns_iam_role_policy
      version: 7
    roles:
      - id: Owner
        name: Owner
        permissions:
          - roles/owner
      - id: Editor
        name: Editor
        permissions:
          - roles/editor
      - id: Viewer
        name: Viewer
        permissions:
          - roles/viewer
      - id: Viewer
        name: Viewer
        permissions:
          - roles/viewer
```
